#!/bin/bash
osbuild="2311_1"
# support custom OS Build
osbuildcodename="\"Eusoumafoca\""
# support custom OS Build Codename
osname="Floflis"
# support custom OS Name
osversion="19"
# support custom OS Version
osfullname="$osname $osversion build $osbuild $osbuildcodename"
# support custom OS FullName
updatepatch="0"
# support custom OS Updatepatch
year="2023"
layer="dna"
nxtlayer="core"
distrobase="blank"
user="blank"
# install="new" # new, ok
specialbuildattempt="47"

case "${nameOutS}"$(uname -s) in
    Linux*)     flofmach="Linux";;
    Darwin*)    flofmach="Mac";;
    CYGWIN*)    flofmach="Cygwin";; # if 64-bit, Cygwin isn't detected
    MINGW*)     flofmach="MinGw";;
    FreeBSD*)   flofmach="FreeBSD";;
    GNU*)       flofmach="GNU";;
    *)          flofmach="UNKNOWN:${nameOutD}"
esac
#echo ${flofmach}

case "${nameOutD}"$(awk -F= '/^NAME/{print $2}' /etc/os-release | tr -d '"') in
    Debian*)     flofdistro=Debian;;
    Ubuntu*)     flofdistro=Ubuntu;;
    *)          flofdistro="UNKNOWN:${nameOutD}"
esac
#echo ${flofdistro}

unameOutM="$(uname -m)"
case "${unameOutM}" in
    i286)   flofarch="286";;
    i586)   flofarch="586";;
    i386)   flofarch="386";;
    i686)   flofarch="386";;
    x86_64) flofarch="amd64";;
    arm)    dpkg --print-flofarch | grep -q "arm64" && flofarch="arm64" || flofarch="arm";;
    riscv64) flofarch="riscv64"
esac
#echo ${flofarch}
