#!/bin/bash
osname="Floflis 20 build 2101 'Eusoumafoca'"
# support custom OS name
osbuild="2101"
# support custom OS build
updatepatch="0"
# support custom OS updatepatch
year="2021"
layer="dna"
nxtlayer="core"
distrobase="blank"
user="blank"
# install="new" # new, ok

unameOutS="$(uname -s)"
case "${unameOut}" in
    Linux*)     flofmach="Linux";;
    Darwin*)    flofmach="Mac";;
    CYGWIN*)    flofmach="Cygwin";;
# if 64-bit, Cygwin isn't detected
    MINGW*)     flofmach="MinGw";;
    FreeBSD*)   flofmach="FreeBSD";;
    GNU*)       flofmach="GNU"
#    *)          flofmach="UNKNOWN:${unameOutS}"
esac
echo ${flofmach}

case "${nameOutD}"$(awk -F= '/^NAME/{print $2}' /etc/os-release) in
    Debian*)     flofdistro=Debian
#    *)          flofdistro="UNKNOWN:${nameOutD}"
esac
echo ${flofdistro}

unameOutM="$(uname -m)"
case "${unameOutM}" in
    i286)   flofarch="286";;
    i386)   flofarch="386";;
    i686)   flofarch="386";;
    x86_64) flofarch="amd64";;
    arm)    dpkg --print-flofarch | grep -q "arm64" && flofarch="arm64" || flofarch="arm";;
    riscv64) flofarch="riscv64"
esac
echo ${flofarch}
