#!/bin/sh
### BEGIN INIT INFO
# Provides: flo-init
# Required-Start:    $local_fs $syslog $remote_fs dbus
# Required-Stop:     $local_fs $syslog $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start script for Floflis
### END INIT INFO

floflis
